### ISSUE TITLE
Platform error cover.switchbot-curtain - Integration 'switchbot-curtain' not found.

### ISSUE THREAD

**Issue by beyondzvincent** [alextud/ha-switchbot-curtain#16]
after i added those files in config folder and restart HA, i added this to config.yaml

cover:
  - platform: switchbot-curtain
    mac: "xxxxxxxxxxx"
    name: "my room"

then this error shows when i check config, please advice.
![Screenshot 2021-06-03 105912](https://user-images.githubusercontent.com/37067522/120579851-c409a800-c45a-11eb-990d-38b567e5e3ed.png)

**Comment by Palleri** [comment]
Closed? but how
