### ISSUE TITLE
Value not accepted, doesnt find the integration

### ISSUE THREAD

**Issue by mpralle** [alextud/ha-switchbot-curtain#17]
Hello, 
I tried to do everything like the instructions, I hope for your help what I did wrong.
![B1](https://user-images.githubusercontent.com/73435132/121820874-631d7380-cc95-11eb-8daf-412c8172a44e.png)
![B2](https://user-images.githubusercontent.com/73435132/121820875-644ea080-cc95-11eb-848f-336623a6c0b3.png)

**Comment by mpralle** [comment]
I also installed it now via Hacs and tried the debugger, same result

**Comment by Untiring** [comment]
Same issue here!

**Comment by Untiring** [comment]
> I also installed it now via Hacs and tried the debugger, same result

how have you installed it through HACS? I've searched for it there but couldn't find it

**Comment by mpralle** [comment]
> > I also installed it now via Hacs and tried the debugger, same result
> 
> how have you installed it through HACS? I've searched for it there but couldn't find it

you can install custom-integrations through HACS

**Comment by Untiring** [comment]
![image](https://user-images.githubusercontent.com/19589238/122103165-98050400-ce16-11eb-9c91-ba31be0c9c6a.png)
for completion, an image of my situation as well

**Comment by mpralle** [comment]
@Untiring did you fixed it by now?

**Comment by Untiring** [comment]
> @Untiring did you fixed it by now?

sadly no. wouldn't know how - im pretty novice on the whole HA thing

**Comment by Untiring** [comment]
@mpralle I've just discovered that the curtains are recognized, although the configuration still shows the errors. 
![image](https://user-images.githubusercontent.com/19589238/122771911-2958f800-d2a7-11eb-9d5b-b785751a3ef3.png)
I saw in the logs that it did get data from the curtains, so i seached for them in the entities tab and there they are: 
![image](https://user-images.githubusercontent.com/19589238/122772165-61f8d180-d2a7-11eb-9585-6c45ce4d4007.png)
just select both and enable them. now you can set their position by using the slider seen in the first screenshot

**Comment by mpralle** [comment]
thank you for the quick help, as you written, the error is still there, but it works fine :D

**Comment by kkuepper** [comment]
it's missing a hacs.json like [this](https://github.com/cagnulein/switchbot_press/blob/master/hacs.json) or [this](https://github.com/RenierM26/ha-switchbot-curtain/blob/main/hacs.json)
So accepting #11 would prevent this error.
